### ISSUE TITLE
OL52340W has incorrect editions

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary-client#104]
https://openlibrary.org/works/OL52340W/Eleven_plays_of_Henrik_Ibsen has two editions in it that are actually a different book:
https://openlibrary.org/books/OL2321416M/Ibsen's_poems
https://openlibrary.org/books/OL20141699M/Ibsen's_poems

**Comment by LeadSongDog** [comment]
@mekarpeles 
Ok, those editions are now linked under https://openlibrary.org/works/OL16018218W/Dikt as translations into English. 

This is one (relatively minor) case of a broader problem: many classic and/or popular works have been incorrectly catalogued under work records bearing their English translated title, yet they have translations into many languages. Manual edits are not a viable solution, this needs power tools. Dostoyevsky alone has taken me many, many, hours of manual work and he is still incomplete. This comes down to needing to make "translation of" become the work OLID rather than a string, then populate "translated from" with the original language. Alternatively, the translation itself could be a special kind of (derivative) work rather than an edition, with an "author" credit to the translator and some new linkage to the original-language work, though I don't recommend that sort of conflation. 

Similarly editions which are collections of smaller works are ill-handled. We need a healthier structure on which to hang them.

**Comment by tfmorris** [comment]
This specific issue is fixed and the more general feature requests are covered in other issues.

@mekarpeles If you agree, please close this issue.

**Comment by hornc** [comment]
This looks like it has been resolved some time ago.
