### ISSUE TITLE
"Bad author - no name" has 2452 books - investigate cleanup

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#116]
https://openlibrary.org/authors/OL5631454A/Bad_author_-_no_name

Investigate why these exist and whether there is a way to recover author names by re-importing?

**Comment by LeadSongDog** [comment]
@hornc 
A quick sampling suggests the problem was with the U of T marc records originally imported in 2008. The ones I looked at such as OL19561082M have neither 100 nor 700 field, but do have editors at subfield 245 $c . 

Today's U of T catalogue runs newer software. When searched on the ISBN 8798287249 (from field 020) it shows the same edition at https://search.library.utoronto.ca/details?9176151#
They've remedied the handling of non-English characters in the interim. The author (field 100) is still blank, but field 700 is now present.

**Comment by LeadSongDog** [comment]
https://github.com/internetarchive/openlibrary/issues/1530 relates?

**Comment by hornc** [comment]
Thank you @LeadSongDog, I think you may be spot on with the #1530 link, it will be a good test to see if enabling MARC $700 import can fix these records.

I'm working on other import improvements at the moment, but I'll try to get to these soon. I'd rather find a bulk re-import fix for this issue than correct items one by one.

**Comment by hornc** [comment]
see also https://openlibrary.org/authors/OL2624944A/Smith_%28undifferentiated%29  (linked from Wikidata OL property discussion page https://www.wikidata.org/wiki/Property_talk:P648

**Comment by hornc** [comment]
Results of a quick scan to see how many of these No Name works have other authors:
```
zgrep "OL5631454A" ol_dump_works_2021-11-30.txt.gz | egrep "(OL[0-9]+A.*){2,}" > NONAME_multipleauthors.tsv
wc -l NONAME_multipleauthors.tsv
74 NONAME_multipleauthors.tsv
```
Only 74, which is less that I was hoping. After cleaning those up, the next step is to check how many have source MARC records with usable author (or editor) data , and whether reimporting will assign those IDs correctly.

I suspect the current import process will not be able to remove the NO NAME author.

**Comment by hornc** [comment]
at this point, the [name missing] record seems to fulfil a structural purpose to represent records which have been cataloged as `[name missing]`
