### ISSUE TITLE
Include functionality under Author class to return list of works

### ISSUE THREAD

**Issue by rahul-kumi** [internetarchive/openlibrary-client#131]
There is no currently existing functionality that allows for access of responses from the `/authors/<author OLID>/works.json` OpenLibrary JSON API endpoint.

**Comment by rahul-kumi** [comment]
To list the works by a particular author which of the following endpoints would be preferred:
say for example, the author with-
Author OLID : OL3241871A
```https://openlibrary.org/search.json?author=OL3241871A```
OR
```https://openlibrary.org/authors/OL3241871A/works.json```
cc: @hornc, @mekarpeles

**Comment by mekarpeles** [comment]
Sounds like a reasonable feature to me

**Comment by hornc** [comment]
@rahul-kumi Authors is already searchable using the search endpoint using `ol.Author.search()` it's a good point that they do / should produce the same results. I think the intent of the `works.json` endpoint is to be a more direct association of works to an author specified by ID, rather than a search, which is more general purpose and could be 'fuzzy'.  It's good to be aware of, but the `work.json` endpoint exists, and it would be nice if the client could access it too.
