### ISSUE TITLE
Where is URL for full text of a Work stored?

### ISSUE THREAD

**Issue by thadguidry** [internetarchive/openlibrary-client#166]
Is it in the Work JSON schema here via a /type/link ?  Am I looking in the right place?
https://github.com/internetarchive/openlibrary-client/blob/1ee0fdf9a229d10f6a7605ea7774b2db834336da/olclient/schemata/work.schema.json#L35

Or is it under Edition here?
https://github.com/internetarchive/openlibrary-client/blob/1ee0fdf9a229d10f6a7605ea7774b2db834336da/olclient/schemata/edition.schema.json#L51

**Comment by tfmorris** [comment]
Works are metadata only and don't have text. The edition `ocaid` is the key to the directory on Internet Archive with the text.

You don't need an AGPL library to deal with this since it's just a couple of HTTP GETs. Start at the edition https://openlibrary.org/books/OL6599209M.json
and extract the `ocaid` which in this case is `annakarenin00tols`
Then the directory containing all the files is https://archive.org/download/annakarenin00tols
and there's an XML list of available files in https://archive.org/download/annakarenin00tols/annakarenin00tols_files.xml

For raw text, look at https://archive.org/download/annakarenin00tols/annakarenin00tols_djvu.txt
or https://archive.org/download/annakarenin00tols/annakarenin00tols_djvu.xml
Raw OCR output is in https://archive.org/download/annakarenin00tols/annakarenin00tols_abbyy.gz

OCR quality is highly variable, so, depending on the volume, the text can be pretty rough. It also most likely won't have been cleaned of things like running page headers/footers, etc.

**Comment by thadguidry** [comment]
@tfmorris beautifully replied, as always.  Thanks so much!

Context: The reason I asked about this is to see what is left TODO to help Linked Data efforts for Wikidata, from @mekarpeles ask from 3 years ago here on mailing list: https://markmail.org/message/hdz47tf5ayddxrny  So I was going to quickly investigate some and see where things stand.

**Comment by thadguidry** [comment]
Hi Tom,

I've run into another little issue.  That of potentially specifying a
particular page image to download (rather than downloading a whole zip
file).
I noticed that this can be done and found a URL such as this which uses
scale=0 for the maximum resolution that was originally scanned (I think).

https://ia800706.us.archive.org/BookReader/BookReaderImages.php?zip=/29/items/sanfranciscoblue25sanf/sanfranciscoblue25sanf_jp2.zip&file=sanfranciscoblue25sanf_jp2/sanfranciscoblue25sanf_0037.jp2&id=sanfranciscoblue25sanf&scale=0&rotate=0

The key ingredient seems to be the construction of
/sanfranciscoblue25sanf_0037.jp2  which asks for page 37
But I'm unsure on how the BookReader backend might deal with all this (for
instance, is .jp2 always available output form the BookReaderImages?) ... I
didn't find documentation, but only played with it in Firefox browser dev
tools and watched the network activity GETs.

Any ideas how this can be made more robust and potentially could it be
added to the Archive.org Python client you think?

Thad
https://www.linkedin.com/in/thadguidry/

**Comment by hornc** [comment]
Closing as this qn has been addressed.
