### ISSUE TITLE
Perform Diff between two Works/Editions/Authors

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#7]
Just a thought, but a diff function between entries (Works, Editions, Authors) that look like they should be the same would be helpful in deciding which one is better, or what fields need to be merged.

In general I imagine there are three outcomes:

1) One record is clearly better, and the other can be safely discarded  (i.e less good record's attributes are a subset of the better record)
2) There is an obvious way to merge data cleanly (copying missing attributes from one to the other) to make a more complete record
3) There are differences/conflicts within the same attributes and no way to decide programatically what to do, so human editing is required ... or maybe they really are different entities?

First step is to perform the diff though.

**Comment by LeadSongDog** [comment]
@hornc Yes, this looks like an obvious first step. Also discussed at https://github.com/internetarchive/openlibrary/wiki/Merge-Processes

**Comment by tfmorris** [comment]
I think there are two subcases to 3. 

3a. The two objects are clearly different
3b. The two objects are likely represent the same entity, but there's no way to merge them automatically.
3c. It's unclear whether the two objects are the same or not

Or perhaps there should be a separate comparison operator which compares two objects and returns the probability that they represent the same thing.

**Comment by LeadSongDog** [comment]
In case 3c, should seek matches for each name string at ISNI, VIAF and wikidata. For each name match returned (among several found), check which shows the closest match on tombstone dates or work titles. This should in most 3c cases resolve to one of the easier cases.

**Comment by thadguidry** [comment]
The best visualization and workflow for merging records that I have seen and used is a UI side-by-side comparison showing statements/claims next to each other where each individual statement can be selected to overwrite and replace the other, or simply rejected because the statement is lower in quality than the original.  This visualization and concept can be seen and used on FamilySearch.org when you want to merge a Person in your genealogy with another already existing in someone else's.

Works, Editions, and Authors could use this same system for visualizing merging of records.

Video showing how it works:  https://youtu.be/9o6DTDhrDLo?t=210

![image](https://user-images.githubusercontent.com/986438/80099780-a3bbaa00-8534-11ea-969e-9e5452f7cb51.png)

**Comment by hornc** [comment]
OL now has a functioning merge works UI for librarians -- not sure a command line version is required (given the visualisation comments above).

Documentation  for the current merge Works process can be found here: https://github.com/onnotasler/OpenLibraryDocumentation/blob/main/Librarians-Merge-DuplicateWorks.adoc

There is also Author merge documentation in the same location.

Closing as completed.
